### PR TITLE
[Fix]: Fix bug on last Obsidian version, support for moving files and option to disable collapse

### PR DESCRIPTION
**Pull request by Mara-Li**
I used the fork of @zansbang to start my version. They PR is from #56 and start supports for Obsidian 1.5.8.

What's was fixed:
- Root was not able to be sorted: Internally, I choosen to update `getSortedFolderItems` instead of `sort`. This allows to sort directly from the root instead of each folder. Note that roots are registered under "" (empty) in the settings (`data.json`).
- Fixed some css issues in the file explorer head. Now, the icon should be aligned!

What's was added:
- Support for moved/deleted files: Now, the settings should be updated when a file is edited (moved/renamed) or deleted.
- Add an option to disable the collapse in status-bar and ribbon: I think the last Obsidian update handle the ribbon perfectly and this option bored me.
- Update icons in the head of the explorer to use the Obsidian last's icon and also change the icon when using custom sort.

Dep:
- Updated to last Obsidian API version
- Added https://github.com/Fevol/obsidian-typings to get more typings for obsidian and prevent error 

If you want to use my version, I released the [update](https://github.com/Mara-Li/obsidian-bartender/releases/tag/0.5.12).

### CODE REVIEW

**Comment by evgeny-kim** [comment]
Thanks for the fix, works perfect with 1.6.3!

**Comment by Mara-Li** [comment]
Happy to heard that. It takes me the whole sunday to fix :'D

**Comment by looneyapache** [comment]
Thank you! It is working now! Appreciate you fixing it.

**Comment by Lepton-Lee** [comment]
Thanks for your work!😁

**Pull request closed without merging**
